import {
  MdOutlineCompareArrows,
  MdSettings,
  MdClose,
  MdModeEditOutline,
  MdArrowBack,
  MdOutlineSearch,
  MdOutlineArrowForwardIos,
  MdOutlineFacebook,
  MdHttps,
  MdOutlineFormatListBulleted,
  MdTune,
  MdPerson,
  MdMarkEmailRead,
  MdGroups,
  MdFlag,
  MdMapsHomeWork,
  MdNotifications,
  MdOutlineLocationOn,
  MdOutlineOndemandVideo,
  MdOutlinePhotoLibrary,
  MdSettingsSuggest,
  MdVideoCall,
} from 'react-icons/md'
import { GiEarthAmerica } from 'react-icons/gi'
import { HiLockClosed } from 'react-icons/hi'
import { GoTriangleDown } from 'react-icons/go'
import { BiImageAdd, BiWifi, BiZoomIn, BiZoomOut } from 'react-icons/bi'
import {
  BsFillKeyboardFill,
  BsFillExclamationTriangleFill,
  BsEmojiWink,
  BsGlobe,
  BsExclamationSquareFill,
  BsTagsFill,
} from 'react-icons/bs'
import {
  FaMoon,
  FaQuestionCircle,
  FaExpandAlt,
  FaChevronRight,
  FaChevronLeft,
  FaUserFriends,
  FaBookmark,
  FaFacebookMessenger,
  FaUserTag,
} from 'react-icons/fa'
import { RiSettings2Fill } from 'react-icons/ri'
import { AiOutlineBug, AiOutlineLike } from 'react-icons/ai'
import { AiOutlineFieldTime } from 'react-icons/ai'
import { RiFeedbackFill, RiLogoutBoxRFill } from 'react-icons/ri'

export const Icon = {
  AiOutlineBug,
  AiOutlineLike,
  AiOutlineFieldTime,
  MdOutlineCompareArrows,
  MdSettings,
  MdClose,
  MdModeEditOutline,
  MdArrowBack,
  MdOutlineSearch,
  MdMarkEmailRead,
  MdPerson,
  MdGroups,
  MdOutlineFacebook,
  MdOutlineArrowForwardIos,
  MdHttps,
  MdFlag,
  MdMapsHomeWork,
  MdNotifications,
  MdOutlineLocationOn,
  MdOutlineOndemandVideo,
  MdOutlinePhotoLibrary,
  MdSettingsSuggest,
  MdVideoCall,
  MdOutlineFormatListBulleted,
  MdTune,
  GiEarthAmerica,
  GoTriangleDown,
  BsEmojiWink,
  BsFillExclamationTriangleFill,
  BsFillKeyboardFill,
  BsGlobe,
  BsTagsFill,
  BsExclamationSquareFill,
  BiImageAdd,
  BiZoomIn,
  BiZoomOut,
  BiWifi,
  FaMoon,
  FaExpandAlt,
  FaChevronRight,
  FaChevronLeft,
  FaQuestionCircle,
  FaUserFriends,
  FaBookmark,
  FaFacebookMessenger,
  FaUserTag,
  RiSettings2Fill,
  RiFeedbackFill,
  RiLogoutBoxRFill,
  HiLockClosed,
}
