import {
  MdOutlineCompareArrows,
  MdSettings,
  MdClose,
  MdModeEditOutline,
  MdArrowBack,
  MdOutlineSearch,
  MdOutlineArrowForwardIos,
  MdOutlineFacebook,
  MdHttps,
  MdOutlineFormatListBulleted,
  MdTune,
  MdPerson,
  MdMarkEmailRead,
  MdGroups,
  MdFlag,
  MdMapsHomeWork,
  MdNotifications,
  MdOutlineLocationOn,
  MdOutlineOndemandVideo,
  MdOutlinePhotoLibrary,
  MdSettingsSuggest,
  MdVideoCall,
  MdCardTravel,
  MdOutlinePrivateConnectivity,
  MdHome,
  MdPublic,
  MdMoreHoriz,
  MdOutlineNotifications,
  MdOutlineCancelPresentation,
  MdSchedule,
  MdSecurity,
  MdOutlineAutoAwesomeMotion,
  MdOutlineFolderShared,
  MdBookmarkBorder,
  MdOutlineHistory,
} from 'react-icons/md'
import { GiEarthAmerica } from 'react-icons/gi'
import {
  HiLockClosed,
  HiDotsHorizontal,
  HiLink,
  HiOutlineSwitchHorizontal,
  HiPlusSm,
} from 'react-icons/hi'
import { GoTriangleDown } from 'react-icons/go'
import {
  BiImageAdd,
  BiWifi,
  BiZoomIn,
  BiZoomOut,
  BiMessageAltEdit,
} from 'react-icons/bi'
import {
  BsFillKeyboardFill,
  BsFillExclamationTriangleFill,
  BsEmojiWink,
  BsGlobe,
  BsExclamationSquareFill,
  BsTagsFill,
  BsCodeSlash,
  BsList,
} from 'react-icons/bs'
import {
  FaMoon,
  FaQuestionCircle,
  FaExpandAlt,
  FaChevronRight,
  FaChevronLeft,
  FaUserFriends,
  FaBookmark,
  FaFacebookMessenger,
  FaUserGraduate,
  FaUserTag,
  FaEdit,
} from 'react-icons/fa'
import {
  AiOutlineBug,
  AiOutlineLike,
  AiOutlineFieldTime,
  AiOutlineSwitcher,
} from 'react-icons/ai'
import {
  RiFeedbackFill,
  RiLogoutBoxRFill,
  RiSettings2Fill,
} from 'react-icons/ri'
import { TbGridDots, TbDots } from 'react-icons/tb'
import { IoGrid, IoChevronBack } from 'react-icons/io5'
import { ImEnlarge } from 'react-icons/im'

export const Icon = {
  AiOutlineBug,
  AiOutlineLike,
  AiOutlineSwitcher,
  AiOutlineFieldTime,
  MdOutlineCompareArrows,
  MdSettings,
  MdClose,
  MdModeEditOutline,
  MdCardTravel,
  MdOutlinePrivateConnectivity,
  MdPublic,
  MdArrowBack,
  MdOutlineSearch,
  MdMarkEmailRead,
  MdPerson,
  MdGroups,
  MdOutlineFacebook,
  MdOutlineArrowForwardIos,
  MdOutlineNotifications,
  MdOutlineCancelPresentation,
  MdSchedule,
  MdSecurity,
  MdOutlineAutoAwesomeMotion,
  MdOutlineFolderShared,
  MdBookmarkBorder,
  MdOutlineHistory,
  MdHttps,
  MdFlag,
  MdHome,
  MdMoreHoriz,
  MdMapsHomeWork,
  MdNotifications,
  MdOutlineLocationOn,
  MdOutlineOndemandVideo,
  MdOutlinePhotoLibrary,
  MdSettingsSuggest,
  MdVideoCall,
  MdOutlineFormatListBulleted,
  MdTune,
  GiEarthAmerica,
  GoTriangleDown,
  BsEmojiWink,
  BsFillExclamationTriangleFill,
  BsFillKeyboardFill,
  BsGlobe,
  BsList,
  BiMessageAltEdit,
  BsTagsFill,
  BsExclamationSquareFill,
  BiImageAdd,
  BiZoomIn,
  BiZoomOut,
  BsCodeSlash,
  BiWifi,
  FaMoon,
  FaExpandAlt,
  FaChevronRight,
  FaChevronLeft,
  FaEdit,
  FaUserGraduate,
  FaQuestionCircle,
  FaUserFriends,
  FaBookmark,
  FaFacebookMessenger,
  FaUserTag,
  RiSettings2Fill,
  RiFeedbackFill,
  RiLogoutBoxRFill,
  HiLockClosed,
  HiOutlineSwitchHorizontal,
  HiDotsHorizontal,
  HiPlusSm,
  HiLink,
  TbGridDots,
  TbDots,
  IoGrid,
  IoChevronBack,
  ImEnlarge,
}
